# Generated by Django 3.1.4 on 2021-01-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_cost',
            new_name='order_total',
        ),
    ]
